# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Copl < Formula
  desc ""
  homepage "https://github.com/commandplaneio/copl"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/commandplaneio/copl/releases/download/v0.1.2/copl_0.1.2_darwin_amd64.tar.gz"
      sha256 "ae8a87a65baacc460124f31d19b4cf736de56b2701c668dfcf2b8c2fee36adbd"

      def install
        bin.install "copl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/commandplaneio/copl/releases/download/v0.1.2/copl_0.1.2_darwin_arm64.tar.gz"
      sha256 "93406a6717cdd78742e4779d2d1c61fbc0676013ffd101d4ea22e1805331a6b1"

      def install
        bin.install "copl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/commandplaneio/copl/releases/download/v0.1.2/copl_0.1.2_linux_amd64.tar.gz"
      sha256 "10beedc48b846d9d007858f52ee2cd2fd1a462ca5c37325f1e2ff033d3b10a7b"

      def install
        bin.install "copl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/commandplaneio/copl/releases/download/v0.1.2/copl_0.1.2_linux_arm64.tar.gz"
      sha256 "4fb31c4738f962dca6b67680bfb4a7ccf5aac94e2b2fa2c752b6792caca7dd9c"

      def install
        bin.install "copl"
      end
    end
  end
end
