# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Copl < Formula
  desc ""
  homepage "https://github.com/commandplaneio/copl"
  version "0.1.8"

  on_macos do
    on_intel do
      url "https://github.com/commandplaneio/copl/releases/download/v0.1.8/copl_0.1.8_darwin_amd64.tar.gz"
      sha256 "c20034f206989b89e0cf8653006db0624e2e575a5c1c409c4af8f5ffe4dc0415"

      def install
        bin.install "copl"
      end
    end
    on_arm do
      url "https://github.com/commandplaneio/copl/releases/download/v0.1.8/copl_0.1.8_darwin_arm64.tar.gz"
      sha256 "a75bd230b31c85c41ac12b8321256f70fa252dd53410ea5fa7d9ed3dbba87f2f"

      def install
        bin.install "copl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/commandplaneio/copl/releases/download/v0.1.8/copl_0.1.8_linux_amd64.tar.gz"
        sha256 "61d093dc3e7e9351550cf682ec3cebea4d8bfdbdaa7aa70d498462d4a355b29c"

        def install
          bin.install "copl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/commandplaneio/copl/releases/download/v0.1.8/copl_0.1.8_linux_arm64.tar.gz"
        sha256 "c2473303cd2fa1eed5257145e6b06a392e1ca88e79640d2407cb9b37df5c27f7"

        def install
          bin.install "copl"
        end
      end
    end
  end
end
